%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontFamily": "Source Serif Pro",
    "fontSize": "16px"  }
}}%%
graph LR;
    A[Polymer Classification] --> B[According to origin]
    B --> B1[Natural, synthetic...]

    A --> C[According to structure]
    C --> C1[Semicrystalline and amorphous]

    A --> D[According to polymerization mechanism]
    D --> D1[Addition, condensation...]

    A --> E[According to chemical composition]
    E --> E1[Acrylics, vinyls...]

    A --> F[According to applications]
    F --> F1[Elastomers, plastics, fibers, adhesives...]

    A --> G[According to their behavior with temperature]
    G --> G1[Thermoplastic, thermosetting...]