%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontFamily": "Source Serif Pro",
    "fontSize": "16px"  }
}}%%
graph TD;
    A[Polymerics] --> B[Thermoplastics]
    A --> C[ Elastomers, or Rubber]
    A --> D[Thermoset Plastics]