%%{init: {
  "theme": "default",
  "themeVariables": {
    "fontFamily": "Source Serif Pro",
    "fontSize": "16px"  }
}}%%
graph LR;
    A[Polymerics] --> B[Thermoplastics]

    B --> C[Polyethylene Terephthalate **PET** - #1]
    B --> D[High-Density Polyethylene **HDPE** - #2]
    B --> E[Polyvinyl Chloride **PVC** - #3]
    B --> F[Low-Density Polyethylene **LDPE** - #4]
    B --> G[Polypropylene **PP** - #5]
    B --> H[Polystyrene **PS** - #6]
    B --> I[Other Plastics **PLA, ABS**, etc. - #7]